In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [21]:
def split_normalization_and_standardization(path_of_csv: str, random_state: int, test_size: float):
    df = pd.read_csv(path_of_csv)
    
    X = df.iloc[:, :-2]
    y = np.array(df['label'])
    source = np.array(df["source"])
    
    # Split into train & test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state=random_state)
    # Split into train & validation
    X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size = test_size, random_state=random_state)
    
    # Normalization
    min_max_scaler = MinMaxScaler()
    X_train_norm = pd.DataFrame(min_max_scaler.fit_transform(X_train))
    X_validation_norm = pd.DataFrame(min_max_scaler.fit_transform(X_validation))
    X_test_norm = pd.DataFrame(min_max_scaler.fit_transform(X_test))
    
    # Standardization
    standard_scaler = StandardScaler()
    X_train_scaled = pd.DataFrame(standard_scaler.fit_transform(X_train_norm))
    X_validation_scaled = pd.DataFrame(standard_scaler.fit_transform(X_validation_norm))
    X_test_scaled = pd.DataFrame(standard_scaler.fit_transform(X_test_norm))
    
    return X_train_scaled, X_validation_scaled, X_test_scaled, source

In [24]:
X_train, X_validation, X_test, source = split_normalization_and_standardization("./data/dataset.csv", 66, 0.2)

In [25]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071
0,-1.679421,-0.808380,0.361127,-1.707726,-0.742773,0.298454,-1.697906,-0.590114,0.340056,-1.697607,...,0.858151,0.319479,0.653415,0.916472,0.276473,0.651765,0.880240,0.288452,0.672742,0.877747
1,-0.526229,-0.876073,-0.983405,-0.567117,-0.893671,-0.960523,-0.581259,-0.906479,-0.970643,-0.591427,...,-0.725433,-0.931966,-1.041071,-0.813104,-0.953787,-1.065653,-0.839438,-0.899290,-1.009697,-0.851476
2,1.659472,1.601490,1.485645,1.686942,1.644151,1.508058,1.475006,1.459387,1.341627,1.375115,...,1.582075,1.448832,1.366050,1.503024,1.461168,1.360790,1.448481,1.626541,1.576273,1.601951
3,1.605835,1.587952,1.497868,1.632628,1.616715,1.520401,1.624801,1.610692,1.514739,1.593619,...,-0.529370,0.243172,0.447543,-0.391990,0.215720,0.415423,-0.360919,0.168174,0.376757,-0.393305
4,0.117413,0.938099,1.228961,0.152552,0.985689,1.273543,0.140477,0.964205,1.267437,0.132370,...,-1.011987,-1.328766,-1.120252,-1.023661,-1.333496,-1.128677,-1.018882,-1.335297,-1.149900,-1.014052